/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p raucinstallerinterface -c RaucInstallerInterface -i raucdbustypes.h rauc-introspection.xml de.pengutronix.rauc.Installer
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "raucinstallerinterface.h"

/*
 * Implementation of interface class RaucInstallerInterface
 */

RaucInstallerInterface::RaucInstallerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

RaucInstallerInterface::~RaucInstallerInterface()
{
}

