/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p raucinstallerinterface -c RaucInstallerInterface -i raucdbustypes.h rauc-introspection.xml de.pengutronix.rauc.Installer
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef RAUCINSTALLERINTERFACE_H
#define RAUCINSTALLERINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "raucdbustypes.h"

/*
 * Proxy class for interface de.pengutronix.rauc.Installer
 */
class RaucInstallerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "de.pengutronix.rauc.Installer"; }

public:
    RaucInstallerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~RaucInstallerInterface();

    Q_PROPERTY(QString BootSlot READ bootSlot)
    inline QString bootSlot() const
    { return qvariant_cast< QString >(property("BootSlot")); }

    Q_PROPERTY(QString Compatible READ compatible)
    inline QString compatible() const
    { return qvariant_cast< QString >(property("Compatible")); }

    Q_PROPERTY(QString LastError READ lastError)
    inline QString lastError() const
    { return qvariant_cast< QString >(property("LastError")); }

    Q_PROPERTY(QString Operation READ operation)
    inline QString operation() const
    { return qvariant_cast< QString >(property("Operation")); }

    Q_PROPERTY(RaucProgress Progress READ progress)
    inline RaucProgress progress() const
    { return qvariant_cast< RaucProgress >(property("Progress")); }

    Q_PROPERTY(QString Variant READ variant)
    inline QString variant() const
    { return qvariant_cast< QString >(property("Variant")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> GetPrimary()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetPrimary"), argumentList);
    }

    inline QDBusPendingReply<RaucSlotStatusArray> GetSlotStatus()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetSlotStatus"), argumentList);
    }

    inline QDBusPendingReply<QString, QString> Info(const QString &bundle)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(bundle);
        return asyncCallWithArgumentList(QStringLiteral("Info"), argumentList);
    }
    inline QDBusReply<QString> Info(const QString &bundle, QString &version)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(bundle);
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QStringLiteral("Info"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            version = qdbus_cast<QString>(reply.arguments().at(1));
        }
        return reply;
    }

    inline QDBusPendingReply<QVariantMap> InspectBundle(const QString &source, const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(source) << QVariant::fromValue(args);
        return asyncCallWithArgumentList(QStringLiteral("InspectBundle"), argumentList);
    }

    inline QDBusPendingReply<> Install(const QString &source)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(source);
        return asyncCallWithArgumentList(QStringLiteral("Install"), argumentList);
    }

    inline QDBusPendingReply<> InstallBundle(const QString &source, const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(source) << QVariant::fromValue(args);
        return asyncCallWithArgumentList(QStringLiteral("InstallBundle"), argumentList);
    }

    inline QDBusPendingReply<QString, QString> Mark(const QString &state, const QString &slot_identifier)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(state) << QVariant::fromValue(slot_identifier);
        return asyncCallWithArgumentList(QStringLiteral("Mark"), argumentList);
    }
    inline QDBusReply<QString> Mark(const QString &state, const QString &slot_identifier, QString &message)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(state) << QVariant::fromValue(slot_identifier);
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QStringLiteral("Mark"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            message = qdbus_cast<QString>(reply.arguments().at(1));
        }
        return reply;
    }

Q_SIGNALS: // SIGNALS
    void Completed(int result);
};

namespace de {
  namespace pengutronix {
    namespace rauc {
      typedef ::RaucInstallerInterface Installer;
    }
  }
}
#endif
